import json
from datetime import datetime
from io import BytesIO
import structlog

logger = structlog.get_logger()


def export_json(job, features, candidates, report) -> str:
    """Export job results as structured JSON."""
    data = {
        "job_id": str(job.id),
        "status": job.status,
        "created_at": job.created_at.isoformat() if job.created_at else None,
        "image_source": job.image_source,
        "source_url": job.source_url,
        "features": {
            "sha256": features.sha256 if features else None,
            "phash": features.phash if features else None,
            "dhash": features.dhash if features else None,
            "ahash": features.ahash if features else None,
            "dimensions": features.dimensions if features else None,
            "mime_type": features.mime_type if features else None,
            "ocr_text": features.ocr_text if features else None,
            "exif_data": features.exif_data if features else None,
        },
        "report": {
            "summary": report.summary if report else None,
            "ai_description": report.ai_description if report else None,
            "entities": report.entities if report else None,
            "search_terms": report.search_terms if report else None,
            "cluster_count": report.cluster_count if report else None,
        },
        "candidates": [
            {
                "source_url": c.source_url,
                "page_title": c.page_title,
                "match_type": c.match_type,
                "similarity_score": c.similarity_score,
                "confidence": c.confidence,
                "extracted_text": c.extracted_text,
            }
            for c in candidates
        ],
        "exported_at": datetime.utcnow().isoformat(),
    }
    return json.dumps(data, indent=2, default=str)


def export_html_report(job, features, candidates, report) -> str:
    """Generate HTML report for PDF conversion or standalone viewing."""
    candidates_html = ""
    for c in (candidates or [])[:20]:
        conf_pct = f"{(c.confidence or 0) * 100:.0f}%"
        candidates_html += f"""
        <tr>
            <td>{c.page_title or 'Untitled'}</td>
            <td>{c.match_type}</td>
            <td>{conf_pct}</td>
            <td><a href="{c.source_url or '#'}">{(c.source_url or '')[:60]}</a></td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TraceLens Report - {str(job.id)[:8]}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #1a1a2e; line-height: 1.6; }}
        h1 {{ color: #4f46e5; border-bottom: 2px solid #e0e7ff; padding-bottom: 8px; }}
        h2 {{ color: #6366f1; margin-top: 32px; }}
        .meta {{ color: #6b7280; font-size: 0.9em; }}
        .summary {{ background: #f5f3ff; padding: 16px; border-radius: 8px; border-left: 4px solid #6366f1; margin: 16px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 0.9em; }}
        th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }}
        th {{ background: #f9fafb; font-weight: 600; }}
        .features {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 0.85em; }}
        .features dt {{ color: #6b7280; }}
        .features dd {{ margin: 0 0 8px 0; font-family: monospace; word-break: break-all; }}
        a {{ color: #4f46e5; }}
    </style>
</head>
<body>
    <h1>TraceLens Investigation Report</h1>
    <p class="meta">Job ID: {job.id}<br>Created: {job.created_at}<br>Status: {job.status}</p>

    <h2>Summary</h2>
    <div class="summary">{report.summary if report else 'No summary available.'}</div>

    <h2>Image Features</h2>
    <dl class="features">
        <dt>SHA-256</dt><dd>{features.sha256 if features else 'N/A'}</dd>
        <dt>pHash</dt><dd>{features.phash if features else 'N/A'}</dd>
        <dt>Dimensions</dt><dd>{features.dimensions if features else 'N/A'}</dd>
        <dt>MIME Type</dt><dd>{features.mime_type if features else 'N/A'}</dd>
        <dt>OCR Text</dt><dd>{(features.ocr_text or 'None')[:200] if features else 'N/A'}</dd>
    </dl>

    <h2>Search Results ({len(candidates or [])} candidates)</h2>
    <table>
        <thead><tr><th>Title</th><th>Match Type</th><th>Confidence</th><th>Source</th></tr></thead>
        <tbody>{candidates_html}</tbody>
    </table>

    <p class="meta" style="margin-top: 32px; font-size: 0.8em;">Generated by TraceLens &bull; {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
</body>
</html>"""
    return html
